spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: ru.mirea.docflow.controller
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5433/doc-flow
    platform: postgresql
