import { makeStyles } from "@material-ui/core/styles";
export const useStyles = makeStyles((theme) => ({
  root: {
    width: "100vw",
    height: "94vh",
    margin: 0,
    padding: 0,
    background: ["rgba(0, 0, 0, 0.5)", "!important"],
    display: "flex",
  },

  doc: {
    position: "absolute",
    left: "25%",
    top: "10%",
    width: "50vw",
    height: "80vh",
  },
  listWrapper: {
    justifySelf: "center",
    alignSelf: "center",
    width: "40vw",
    height: "80vh",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    margin: "auto",
    background: "linear-gradient(top, #7F8C8D, #000000)",
    padding: "0px 0px",
  },
  table: {
    width: "100%",
    fontFamily: "Lato, sans-serif",
    borderSpacing: 0,
    borderCollapse: "separate",
  },
  header: {
    margin: 0,
    padding: 0,
    boxSizing: "border-box",
  },
  headerRow: {
    height: "100%",
    width: "100%",
    borderBottom: "1px solid white",
    fontWeight: "bold",
    fontSize: 20,
    backgroundColor: "#6c7ae0",
    color: "#fff",
    lineHeight: 1.4,
    paddingTop: 18,
    paddingBottom: 18,
  },
  tableBody: {
    borderSpacing: ["0", "1em", "!important"],
    borderCollapse: "separate",
  },
  title: {
    width: "50%",
    textAlign: "start",
    backgroundColor: "#6c7ae0",
    color: "#fff",
    paddingTop: 9,
    paddingBottom: 9,
  },
  date: {
    width: "40%",
    textAlign: "start",
    backgroundColor: "#6c7ae0",
    color: "#fff",
    paddingTop: 9,
    paddingBottom: 9,
  },
  share: {
    width: "10%",
    textAlign: "start",
    backgroundColor: "#6c7ae0",
    color: "#fff",
    paddingTop: 9,
    paddingBottom: 9,
  },
}));
