version: '3.7'
services:
  postgres:
    image: postgres:11
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "doc-flow"
      COMPOSE_CONVERT_WINDOWS_PATHS: "false"
    restart: always